CREATE TABLE transactions (
    id SERIAL PRIMARY KEY,
    trans_date_trans_time TIMESTAMP NOT NULL,
    cc_num BIGINT NOT NULL,
    merchant VARCHAR(255) NOT NULL,
    category VARCHAR(50) NOT NULL,
    trans_amount DECIMAL(10, 2) NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    gender CHAR(1) NOT NULL,
    street VARCHAR(255) NOT NULL,
    city VARCHAR(100) NOT NULL,
    state_code CHAR(2) NOT NULL,
    zip VARCHAR(10) NOT NULL,
    latitude DECIMAL(9, 6),
    longitude DECIMAL(9, 6),
    city_population INT NOT NULL,
    job VARCHAR(100),
    dob DATE NOT NULL,
    trans_num VARCHAR(50) NOT NULL,
    unix_time BIGINT NOT NULL,
    merch_lat DECIMAL(9, 6),
    merch_long DECIMAL(9, 6),
    is_fraud BOOLEAN NOT NULL,
	CONSTRAINT check_dob CHECK (dob BETWEEN '1920-01-01' AND '2020-01-01'),
	CONSTRAINT check_gender CHECK (gender IN ('M', 'F')),
	CONSTRAINT check_state CHECK (state_code ~ '^[A-Z]{2}$'),
	CONSTRAINT check_lat CHECK (latitude BETWEEN -90 AND 90),
	CONSTRAINT check_long CHECK (longitude BETWEEN -180 AND 180),
	CONSTRAINT check_merch_lat CHECK (merch_lat BETWEEN -90 AND 90),
	CONSTRAINT check_merch_long CHECK (merch_long BETWEEN -180 AND 180),
	CONSTRAINT check_trans_date CHECK (trans_date_trans_time BETWEEN '2010-01-01' AND '2030-12-31')
);

-- Se realiza mediante psql para evitar inconvenientes con superusuario en SupaBase
COPY transactions(
    trans_date_trans_time,
    cc_num,
    merchant,
    category,
    trans_amount, 
    first_name,
    last_name,
    gender,
    street,
    city,
    state_code,
    zip,
    latitude,
    longitude,
    city_population,
    job,
    dob,
    trans_num,
    unix_time,
    merch_lat,
    merch_long,
    is_fraud
)
FROM 'D:\no-country\data\ccard_fraud.csv'
WITH (FORMAT CSV, HEADER, DELIMITER ',',QUOTE '"');